 name: Build AMI with Packer
 
on:
  push:
    branches:
      - main

jobs:
  build-ami:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: '1.10.2'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Initialize Packer
        run: |
          cd packer
          packer init .

      - name: Validate Packer templates
        run: |
          cd packer
          packer validate .

      - name: Build AMI with Packer and save logs
        id: build_ami
        run: |
          cd packer
          packer build -machine-readable . | tee build.log

      - name: Debug: Show last 20 lines of build.log
        run: |
          cd packer
          tail -n 20 build.log

      - name: Extract AMI ID from logs
        id: extract_ami
        run: |
          cd packer
          AMI_ID=$(awk -F, '/artifact,0,id/ {print $NF}' build.log | awk -F: '{print $2}' | tail -n1)
          echo "AMI_ID=$AMI_ID"
          if [ -z "$AMI_ID" ]; then
            echo "AMI ID extraction failed!"
            exit 1
          fi
          echo "ami_id=$AMI_ID" >> $GITHUB_OUTPUT

      - name: Show AMI ID
        run: echo "Built AMI ID is ${{ steps.extract_ami.outputs.ami_id }}"
